name: ids_qrcode_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bloc: ^8.1.3
  build_runner: ^2.4.8
  connectivity_plus: ^2.3.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  meta: ^1.11.0
  mobile_scanner: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
